##TODO: define params
_target_: src.models.model.ADModel
batch_size: ${datamodule.batch_size} #specified in the global config.yaml of the patent caller
lr: 0.0008
hidden_dim_1: 640
hidden_dim_2: 320
seq_length: 32

#number of features will be calculated automatically as the number of originally considered features minus number of features to ignore
features_to_ignore: ${preprocessor.features_to_ignore}
