# @package _global_

###################################################################################
# SET PARAMS
###################################################################################

dataset_to_explain_path: /tmp/ad/data/2022-12-25_23-00-00_log-data.csv
model_version: 2022-12-24_23-00-00
outlier_threshold: 0.99

###################################################################################





###################################################################################
# LEAVE AS IS!
###################################################################################
defaults:
  - _self_
  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog
original_work_dir: ${hydra:runtime.cwd}
data_dir: ${original_work_dir}/data/
###################################################################################